// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MovieYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            BannerUrl = "littlemermaid.jpg",
                            Description = "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.",
                            MovieYear = "2023",
                            Title = "The Little Mermaid"
                        },
                        new
                        {
                            Id = 1001,
                            BannerUrl = "barbie.jpg",
                            Description = "A doll living in 'Barbie land' is expelled for not being perfect enough and sets off on an adventure in the real world. A Live-action feature film based on the popular line of Barbie toys.",
                            MovieYear = "2023",
                            Title = "Barbie"
                        },
                        new
                        {
                            Id = 1002,
                            BannerUrl = "Oppenheimer.jpg",
                            Description = "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
                            MovieYear = "2023",
                            Title = "Oppenheimer"
                        },
                        new
                        {
                            Id = 1003,
                            BannerUrl = "Flash.jpg",
                            Description = "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
                            MovieYear = "2023",
                            Title = "The Flash"
                        },
                        new
                        {
                            Id = 1004,
                            BannerUrl = "JohnWick4.jpg",
                            Description = "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes",
                            MovieYear = "2023",
                            Title = "John Wick: Chapter 4"
                        },
                        new
                        {
                            Id = 1005,
                            BannerUrl = "Spider-man-across.jpg",
                            Description = "The continuing story of Miles Morales and the many other Spider-People from different realities.",
                            MovieYear = "2023",
                            Title = "Spider-Man: Across the Spider-Verse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
